title: Lutalli

url: https://lutalli.com
permalink: /:categories/:title

plugins:
  - jekyll-feed

highlighter: none

excerpt_separator: "\n\n~~~"

collections:
  codex:
    output: true
    permalink: /codex/:title

defaults:
  - values:
      layout: default
